### ISSUE TITLE
Sorting of folders on left sidebar don't seem to work

### ISSUE THREAD

**Issue by alicangok** [ppeetteerrs/obsidian-zola#10]
Even though my [netlify.toml](https://github.com/alicangok/Alican-s-Notes/blob/main/netlify.toml) contains an explicit "SORT_BY = "title" line (which is supposed to be the default sorting method even if not given), the sorting of the folders on the left sidebar do not follow this rule. 

This is also the case the [example site](https://peteryuen.netlify.app/docs/home/). "University" should come later than "Deep Learning", etc., right?

<img width="330" alt="image" src="https://user-images.githubusercontent.com/26303095/162624821-5b1b864c-bbb1-401a-bcb7-95c70feaec0a.png">

**Comment by ppeetteerrs** [comment]
Hi, thanks for noticing that. I have included sorting of subsections by title as the default behaviour. Unfortunately, Zola SSG does not offer built-in sorting of subsections (random if no weights are assigned) so that was done in Python by manually assigning section weights. If there are future requests on configurable sorting logic I might consider adding that in.

**Comment by ppeetteerrs** [comment]
Solved here: 38497498a7b3590c01a5489ad20fed1ff8d7894a
