### ISSUE TITLE
Add graph view

### ISSUE THREAD

**Issue by legend053** [ppeetteerrs/obsidian-zola#2]
Is there a way to add graph view for notes connection?

**Comment by ppeetteerrs** [comment]
That would be quite a bit of work I believe, since I am not sure how to extract the graph data from the obsidian vault at the moment. Some CSS + Rust handling would probably be needed on the Zola side. This repo is currently intended as a simple fuzz-free alternative to Obsidian Publish for basic sharing but I do hope that somebody can fork it / submit pull requests to add in more nice features!!

**Comment by ppeetteerrs** [comment]
I will leave the issue opened so that anyone who is interested to contribute can see it :)

**Comment by ppeetteerrs** [comment]
Neo4j would be relevant if myself / anyone has spare time to implement a built-in graph view, but back-link parsing needs to be implemented first.

**Comment by ppeetteerrs** [comment]
Beta support for graph view is available now in `dev` branch. Please refer to [example repo's](https://github.com/ppeetteerrs/obsidian-pkm) `netlify.toml` on fetching from `dev` branch.

ab82cdda091129af891375201445a4ffbfc277db

**Comment by ppeetteerrs** [comment]
Officially supported: 7809c68ae5adca1be34f51f0a89f4e23e700d5f3
