### ISSUE TITLE
Issue with Math Notation

### ISSUE THREAD

**Issue by DuckStroll** [ppeetteerrs/obsidian-zola#21]
It seems like some matrices do not render:
![image](https://user-images.githubusercontent.com/103377430/167740102-32d57685-46e5-4839-b522-9a310ebe45fa.png)
This works in obsidian but doesn't work in the website
![image](https://user-images.githubusercontent.com/103377430/167740204-7634c550-1f46-4dd1-b49d-dcff4a69b67f.png)
it gives me this in the website
![image](https://user-images.githubusercontent.com/103377430/167740469-00bcc3bd-f7b7-4fb7-979e-e1739cc160e5.png)
Similarly, line break seem to get deleted from matrices
![image](https://user-images.githubusercontent.com/103377430/167741025-9c81944c-aafe-4c86-ba21-412fd92d2302.png)
instead of 
![image](https://user-images.githubusercontent.com/103377430/167741050-09fd145c-c237-44b3-95e8-13f825b47031.png)
Anyway, most digital garden for obsidian have this issue,
 so if you find the way to solve this it would be amazing.

**Comment by ppeetteerrs** [comment]
I think I have mentioned somewhere that you would need to turn on `STRICT_LINE_BREAKS=y` in order to use the Maths notation properly (i.e. you need two linebreaks for a new line, you can turn on strict line breaks in Obsidian such that you get the same behaviour). The idea behind is that it is rather complex to figure out which line is part of a Maths equation and which line is not. If strict line break is not applied, your document format might get messed up.
